In [1]:
import pandas as pd

df = pd.read_csv('produtos.csv', sep=',')
display(df)
display(df.info())

,Title,Price
0,A Light in the ...,£51.77\n\n In stock\n\nAdd to basket
1,Tipping the Velvet,£53.74\n\n In stock\n\nAdd to basket
2,Soumission,£50.10\n\n In stock\n\nAdd to basket
3,Sharp Objects,£47.82\n\n In stock\n\nAdd to basket
4,Sapiens: A Brief History ...,£54.23\n\n In stock\n\nAdd to basket
5,The Requiem Red,£22.65\n\n In stock\n\nAdd to basket
6,The Dirty Little Secrets ...,£33.34\n\n In stock\n\nAdd to basket
7,The Coming Woman: A ...,£17.93\n\n In stock\n\nAdd to basket
8,The Boys in the ...,£22.60\n\n In stock\n\nAdd to basket
9,The Black Maria,£52.15\n\n In stock\n\nAdd to basket
10,Starving Hearts (Triangular Trade ...,£13.99\n\n In stock\n\nAdd to basket
11,Shakespeare's Sonnets,£20.66\n\n In stock\n\nAdd to basket
12,Set Me Free,£17.46\n\n In stock\n\nAdd to basket
13,Scott Pilgrim's Precious Little ...,£52.29\n\n In stock\n\nAdd to basket
14,Rip it Up and ...,£35.02\n\n In stock\n\nAdd to basket
15,Our Band Could Be ...,£57.25\n\n In stock\n\nAdd to basket
16,Olio,£23.88\n\n In stock\n\nAdd to basket
17,Mesaerion: The Best Science ...,£37.59\n\n In stock\n\nAdd to basket
18,Libertarianism for Beginners,£51.33\n\n In stock\n\nAdd to basket
19,It's Only the Himalayas,£45.17\n\n In stock\n\nAdd to basket
20,In Her Wake,£12.84\n\n In stock\n\nAdd to basket
21,How Music Works,£37.32\n\n In stock\n\nAdd to basket
22,Foolproof Preserving: A Guide ...,£30.52\n\n In stock\n\nAdd to basket
23,Chase Me (Paris Nights ...,£25.27\n\n In stock\n\nAdd to basket
24,Black Dust,£34.53\n\n In stock\n\nAdd to basket
25,Birdsong: A Story in ...,£54.64\n\n In stock\n\nAdd to basket
26,America's Cradle of Quarterbacks: ...,£22.50\n\n In stock\n\nAdd to basket
27,Aladdin and His Wonderful ...,£53.13\n\n In stock\n\nAdd to basket
28,Worlds Elsewhere: Journeys Around ...,£40.30\n\n In stock\n\nAdd to basket
29,Wall and Piece,£44.18\n\n In stock\n\nAdd to basket
30,The Four Agreements: A ...,£17.66\n\n In stock\n\nAdd to basket
31,The Five Love Languages: ...,£31.05\n\n In stock\n\nAdd to basket
32,The Elephant Tree,£23.82\n\n In stock\n\nAdd to basket
33,The Bear and the ...,£36.89\n\n In stock\n\nAdd to basket
34,Sophie's World,£15.94\n\n In stock\n\nAdd to basket

<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   35 non-null     str
 1   Price   35 non-null     str
dtypes: str(2)
memory usage: 692.0 bytes

None

In [2]:
df["Price"] = df["Price"].str.extract(r"£(\d+\.\d+)").astype(float)
livro_barato = df[df['Price'] < 20]

In [3]:
display(df)
display(livro_barato)

                                    Title  Price
0                      A Light in the ...  51.77
1                      Tipping the Velvet  53.74
2                              Soumission  50.10
3                           Sharp Objects  47.82
4            Sapiens: A Brief History ...  54.23
5                         The Requiem Red  22.65
6            The Dirty Little Secrets ...  33.34
7                 The Coming Woman: A ...  17.93
8                     The Boys in the ...  22.60
9                         The Black Maria  52.15
10  Starving Hearts (Triangular Trade ...  13.99
11                  Shakespeare's Sonnets  20.66
12                            Set Me Free  17.46
13    Scott Pilgrim's Precious Little ...  52.29
14                      Rip it Up and ...  35.02
15                  Our Band Could Be ...  57.25
16                                   Olio  23.88
17        Mesaerion: The Best Science ...  37.59
18           Libertarianism for Beginners  51.33
19                It's Only the Himalayas  45.17
20                            In Her Wake  12.84
21                        How Music Works  37.32
22      Foolproof Preserving: A Guide ...  30.52
23             Chase Me (Paris Nights ...  25.27
24                             Black Dust  34.53
25               Birdsong: A Story in ...  54.64
26  America's Cradle of Quarterbacks: ...  22.50
27          Aladdin and His Wonderful ...  53.13
28  Worlds Elsewhere: Journeys Around ...  40.30
29                         Wall and Piece  44.18
30             The Four Agreements: A ...  17.66
31           The Five Love Languages: ...  31.05
32                      The Elephant Tree  23.82
33                   The Bear and the ...  36.89
34                         Sophie's World  15.94

                                    Title  Price
7                 The Coming Woman: A ...  17.93
10  Starving Hearts (Triangular Trade ...  13.99
12                            Set Me Free  17.46
20                            In Her Wake  12.84
30             The Four Agreements: A ...  17.66
34                         Sophie's World  15.94

In [4]:
df = pd.DataFrame(livro_barato)
df.to_csv('livros_baratos.csv', index=False)
df = pd.read_csv('livros_baratos.csv')
display(df)

                                   Title  Price
0                The Coming Woman: A ...  17.93
1  Starving Hearts (Triangular Trade ...  13.99
2                            Set Me Free  17.46
3                            In Her Wake  12.84
4             The Four Agreements: A ...  17.66
5                         Sophie's World  15.94

In [5]:
df = pd.read_csv('LIVROS_FILTRADOS.csv', sep=',')
display(df)

   Unnamed: 0                                  Title  Price
0          20                            In Her Wake  12.84
1          10  Starving Hearts (Triangular Trade ...  13.99
2          34                         Sophie's World  15.94
3          12                            Set Me Free  17.46
4          30             The Four Agreements: A ...  17.66
5           7                The Coming Woman: A ...  17.93